[2023-02-14T21:30:04.778+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-14T21:25:02.839204+00:00 [queued]>
[2023-02-14T21:30:04.789+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-14T21:25:02.839204+00:00 [queued]>
[2023-02-14T21:30:04.790+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:30:04.791+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-14T21:30:04.792+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:30:04.809+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-14 21:25:02.839204+00:00
[2023-02-14T21:30:04.815+0000] {standard_task_runner.py:55} INFO - Started process 2403 to run task
[2023-02-14T21:30:04.819+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-14T21:25:02.839204+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpnnoi3zhb']
[2023-02-14T21:30:04.821+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask test_***
[2023-02-14T21:30:04.890+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-14T21:25:02.839204+00:00 [running]> on host 55b685598511
[2023-02-14T21:30:04.956+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T21:25:02.839204+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T21:25:02.839204+00:00
[2023-02-14T21:30:04.960+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T21:30:04.962+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 scraper_specific.py']
[2023-02-14T21:30:04.975+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T21:30:05.058+0000] {subprocess.py:93} INFO - python3: can't open file 'scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T21:30:05.061+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T21:30:05.074+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T21:30:05.078+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=abc, task_id=test_***, execution_date=20230214T212502, start_date=20230214T213004, end_date=20230214T213005
[2023-02-14T21:30:05.091+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 59 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 2403)
[2023-02-14T21:30:05.112+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T21:30:05.132+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
