[2023-02-15T15:45:24.144+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:45:22.518401+00:00 [queued]>
[2023-02-15T15:45:24.158+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:45:22.518401+00:00 [queued]>
[2023-02-15T15:45:24.160+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:45:24.161+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-02-15T15:45:24.162+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:45:24.182+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-15 15:45:22.518401+00:00
[2023-02-15T15:45:24.189+0000] {standard_task_runner.py:55} INFO - Started process 42117 to run task
[2023-02-15T15:45:24.194+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-15T15:45:22.518401+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpbljdq1ao']
[2023-02-15T15:45:24.196+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask test_***
[2023-02-15T15:45:24.280+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-15T15:45:22.518401+00:00 [running]> on host 55b685598511
[2023-02-15T15:45:24.367+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T15:45:22.518401+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T15:45:22.518401+00:00
[2023-02-15T15:45:24.371+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T15:45:24.373+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py']
[2023-02-15T15:45:24.392+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T15:45:24.511+0000] {subprocess.py:93} INFO - python3: can't open file '/Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-15T15:45:24.515+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-15T15:45:24.532+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-15T15:45:24.538+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=abc, task_id=test_***, execution_date=20230215T154522, start_date=20230215T154524, end_date=20230215T154524
[2023-02-15T15:45:24.555+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 42117)
[2023-02-15T15:45:24.607+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-15T15:45:24.630+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
