[2023-02-14T21:06:46.990+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-02-14T21:06:47.003+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-02-14T21:06:47.005+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:06:47.006+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-14T21:06:47.008+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:06:47.028+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-08 00:00:00+00:00
[2023-02-14T21:06:47.035+0000] {standard_task_runner.py:55} INFO - Started process 505 to run task
[2023-02-14T21:06:47.048+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'scheduled__2023-02-08T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpdtvej6jr']
[2023-02-14T21:06:47.049+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask test_***
[2023-02-14T21:06:47.163+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow scheduled__2023-02-08T00:00:00+00:00 [running]> on host 55b685598511
[2023-02-14T21:06:47.315+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-08T00:00:00+00:00
[2023-02-14T21:06:47.318+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T21:06:47.323+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ~/scraper_specific.py']
[2023-02-14T21:06:47.341+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T21:06:47.488+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T21:06:47.492+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T21:06:47.506+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T21:06:47.514+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=abc, task_id=test_***, execution_date=20230208T000000, start_date=20230214T210646, end_date=20230214T210647
[2023-02-14T21:06:47.533+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 505)
[2023-02-14T21:06:47.576+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T21:06:47.599+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
