[2023-02-14T21:13:54.262+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-14T21:13:53.350670+00:00 [queued]>
[2023-02-14T21:13:54.274+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-14T21:13:53.350670+00:00 [queued]>
[2023-02-14T21:13:54.275+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:13:54.276+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-02-14T21:13:54.277+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T21:13:54.294+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-14 21:13:53.350670+00:00
[2023-02-14T21:13:54.300+0000] {standard_task_runner.py:55} INFO - Started process 1099 to run task
[2023-02-14T21:13:54.304+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-14T21:13:53.350670+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpdilx08f9']
[2023-02-14T21:13:54.305+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask test_***
[2023-02-14T21:13:54.376+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-14T21:13:53.350670+00:00 [running]> on host 55b685598511
[2023-02-14T21:13:54.442+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T21:13:53.350670+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T21:13:53.350670+00:00
[2023-02-14T21:13:54.445+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T21:13:54.446+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ./dags:/opt/***/dags/scraper_specific.py']
[2023-02-14T21:13:54.460+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T21:13:54.542+0000] {subprocess.py:93} INFO - python3: can't open file './dags:/opt/***/dags/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T21:13:54.545+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T21:13:54.559+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T21:13:54.563+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=abc, task_id=test_***, execution_date=20230214T211353, start_date=20230214T211354, end_date=20230214T211354
[2023-02-14T21:13:54.576+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 1099)
[2023-02-14T21:13:54.597+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T21:13:54.616+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
