[2023-02-14T15:14:19.801+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [queued]>
[2023-02-14T15:14:19.819+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [queued]>
[2023-02-14T15:14:19.820+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:14:19.822+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-02-14T15:14:19.824+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:14:19.847+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-14 15:14:18.545034+00:00
[2023-02-14T15:14:19.856+0000] {standard_task_runner.py:55} INFO - Started process 1186 to run task
[2023-02-14T15:14:19.864+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'simple', 'test_***', 'manual__2023-02-14T15:14:18.545034+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpdss6gt26']
[2023-02-14T15:14:19.866+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask test_***
[2023-02-14T15:14:19.965+0000] {task_command.py:389} INFO - Running <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [running]> on host 55b685598511
[2023-02-14T15:14:20.064+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T15:14:18.545034+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T15:14:18.545034+00:00
[2023-02-14T15:14:20.068+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T15:14:20.070+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py']
[2023-02-14T15:14:20.088+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T15:14:20.217+0000] {subprocess.py:93} INFO - python3: can't open file '/Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T15:14:20.221+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T15:14:20.240+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T15:14:20.247+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=test_***, execution_date=20230214T151418, start_date=20230214T151419, end_date=20230214T151420
[2023-02-14T15:14:20.268+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 31 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 1186)
[2023-02-14T15:14:20.317+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T15:14:20.344+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
