[2023-02-14T15:19:21.341+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [queued]>
[2023-02-14T15:19:21.355+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [queued]>
[2023-02-14T15:19:21.357+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:19:21.358+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-14T15:19:21.359+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:19:21.384+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-14 15:14:18.545034+00:00
[2023-02-14T15:19:21.391+0000] {standard_task_runner.py:55} INFO - Started process 1558 to run task
[2023-02-14T15:19:21.397+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'simple', 'test_***', 'manual__2023-02-14T15:14:18.545034+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpy2lda6s7']
[2023-02-14T15:19:21.399+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask test_***
[2023-02-14T15:19:21.500+0000] {task_command.py:389} INFO - Running <TaskInstance: simple.test_airflow manual__2023-02-14T15:14:18.545034+00:00 [running]> on host 55b685598511
[2023-02-14T15:19:21.603+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T15:14:18.545034+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T15:14:18.545034+00:00
[2023-02-14T15:19:21.606+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T15:19:21.609+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py']
[2023-02-14T15:19:21.630+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T15:19:21.764+0000] {subprocess.py:93} INFO - python3: can't open file '/Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T15:19:21.769+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T15:19:21.788+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T15:19:21.795+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=simple, task_id=test_***, execution_date=20230214T151418, start_date=20230214T151921, end_date=20230214T151921
[2023-02-14T15:19:21.815+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 1558)
[2023-02-14T15:19:21.851+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T15:19:21.880+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
