[2023-02-16T11:02:19.197+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abcd.EXTRACTING_DATA manual__2023-02-16T10:57:08.997860+00:00 [queued]>
[2023-02-16T11:02:19.218+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abcd.EXTRACTING_DATA manual__2023-02-16T10:57:08.997860+00:00 [queued]>
[2023-02-16T11:02:19.220+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T11:02:19.221+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-16T11:02:19.223+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T11:02:19.249+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): EXTRACTING_DATA> on 2023-02-16 10:57:08.997860+00:00
[2023-02-16T11:02:19.259+0000] {standard_task_runner.py:55} INFO - Started process 726 to run task
[2023-02-16T11:02:19.265+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abcd', 'EXTRACTING_DATA', 'manual__2023-02-16T10:57:08.997860+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dag_scrape_specific.py', '--cfg-path', '/tmp/tmphd5c3bb_']
[2023-02-16T11:02:19.267+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask EXTRACTING_DATA
[2023-02-16T11:02:19.395+0000] {task_command.py:389} INFO - Running <TaskInstance: abcd.EXTRACTING_DATA manual__2023-02-16T10:57:08.997860+00:00 [running]> on host 55b685598511
[2023-02-16T11:02:19.522+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=test
AIRFLOW_CTX_DAG_ID=abcd
AIRFLOW_CTX_TASK_ID=EXTRACTING_DATA
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T10:57:08.997860+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T10:57:08.997860+00:00
[2023-02-16T11:02:20.425+0000] {cursor.py:727} INFO - query: [ROLLBACK]
[2023-02-16T11:02:20.573+0000] {cursor.py:740} INFO - query execution done
[2023-02-16T11:02:20.575+0000] {cursor.py:879} INFO - Number of results in first chunk: 1
[2023-02-16T11:02:20.577+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 695, in execute
    query = self._preprocess_pyformat_query(command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 594, in _preprocess_pyformat_query
    query = command % processed_params
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_scrape_specific.py", line 53, in extract_data_send_to_snowflake
    df_test.to_sql('match_results', con=engine, index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2225, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 856, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 840, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2236, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2068, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': not all arguments converted during string formatting
[2023-02-16T11:02:20.596+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=abcd, task_id=EXTRACTING_DATA, execution_date=20230216T105708, start_date=20230216T110219, end_date=20230216T110220
[2023-02-16T11:02:20.619+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 113 for task EXTRACTING_DATA (Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': not all arguments converted during string formatting; 726)
[2023-02-16T11:02:20.644+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-16T11:02:20.688+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
